AllCops:
  StyleGuideCopsOnly: true

Metrics/LineLength:
  Description: 'Limit lines to 120 characters.'
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*_spec.rb'

Metrics/ModuleLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*_spec.rb'

Style/StringLiterals:
  EnforcedStyle: double_quotes